const fs = require('fs');
const path = require('path');

const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

const sdkRoot = path.resolve(__dirname, '../argus-plugin-sdk');
const sdkEntry = path.join(sdkRoot, 'src');

config.watchFolders = [...(config.watchFolders ?? [])];
config.resolver.extraNodeModules = {
  ...(config.resolver.extraNodeModules ?? {}),
};

/**
 * Dev HMR plugins — only from gitignored `dev-plugins.local.json`.
 * No plugins are hard-coded; copy the `.example` file to get started.
 */
function loadDevHmrPluginSpecs() {
  /** @type {{ metroName: string, root: string, src?: string }[]} */
  const specs = [];

  const localPath = path.join(__dirname, 'dev-plugins.local.json');
  if (!fs.existsSync(localPath)) {
    console.info(
      '[metro] no dev-plugins.local.json — HMR plugins disabled (use store mode or copy the .example file)',
    );
    return specs;
  }

  try {
    const raw = JSON.parse(fs.readFileSync(localPath, 'utf8'));
    const list = Array.isArray(raw?.plugins) ? raw.plugins : [];
    for (const entry of list) {
      if (!entry?.metroName || !entry?.root) continue;
      const root = path.resolve(__dirname, entry.root);
      const srcRel = typeof entry.src === 'string' ? entry.src : 'src';
      const srcAbs = path.join(root, srcRel);
      if (!fs.existsSync(srcAbs)) {
        console.warn(
          `[metro] dev-plugins.local.json: skip ${entry.metroName} (missing ${srcAbs})`,
        );
        continue;
      }
      const existing = specs.findIndex((s) => s.metroName === entry.metroName);
      const next = { metroName: entry.metroName, root, src: srcRel };
      if (existing >= 0) specs[existing] = next;
      else specs.push(next);
    }
  } catch (err) {
    console.warn('[metro] failed to read dev-plugins.local.json', err);
  }

  return specs;
}

function registerDevHmrPlugins(specs) {
  const registryPath = path.join(
    __dirname,
    'src/platform/plugins/dev-hmr-registry.generated.js',
  );

  for (const spec of specs) {
    const srcAbs = path.join(spec.root, spec.src ?? 'src');
    if (!config.watchFolders.includes(spec.root)) {
      config.watchFolders.push(spec.root);
    }
    config.resolver.extraNodeModules[spec.metroName] = srcAbs;
  }

  const body = specs
    .map(
      (s) =>
        `  {\n    metroName: ${JSON.stringify(s.metroName)},\n    load: () => require(${JSON.stringify(s.metroName)}),\n  }`,
    )
    .join(',\n');

  const file = `/**\n * AUTO-GENERATED by metro.config.js — do not edit or commit.\n * Source: gitignored dev-plugins.local.json only\n */\nmodule.exports = {\n  modules: [\n${body}\n  ],\n};\n`;

  try {
    const prev = fs.existsSync(registryPath)
      ? fs.readFileSync(registryPath, 'utf8')
      : null;
    if (prev !== file) {
      fs.writeFileSync(registryPath, file);
      console.info(
        `[metro] wrote dev-hmr-registry.generated.js (${specs.length} plugin(s))`,
      );
    }
  } catch (err) {
    console.warn('[metro] could not write dev-hmr-registry.generated.js', err);
  }
}

const devHmrSpecs = loadDevHmrPluginSpecs();
registerDevHmrPlugins(devHmrSpecs);

// Optional local SDK HMR: if a sibling checkout exists, prefer its src/ over node_modules.
// Committed dependency is npm `@argus-tv/plugin-sdk` (CI/EAS); file: is not required.
if (fs.existsSync(path.join(sdkRoot, 'package.json'))) {
  config.watchFolders.push(sdkRoot);
  config.resolver.extraNodeModules['@argus-tv/plugin-sdk'] = fs.existsSync(sdkEntry)
    ? sdkEntry
    : sdkRoot;
}

/**
 * Sibling TS packages use ESM-style `./foo.js` imports that map to `foo.ts`.
 * Remap those relative imports when the `.ts` file exists on disk.
 */
const defaultResolveRequest = config.resolver.resolveRequest;
config.resolver.resolveRequest = (context, moduleName, platform) => {
  if (
    typeof moduleName === 'string' &&
    moduleName.startsWith('.') &&
    moduleName.endsWith('.js') &&
    context.originModulePath
  ) {
    const asTs = path.resolve(
      path.dirname(context.originModulePath),
      moduleName.replace(/\.js$/, '.ts'),
    );
    if (fs.existsSync(asTs)) {
      return { type: 'sourceFile', filePath: asTs };
    }
  }

  if (defaultResolveRequest) {
    return defaultResolveRequest(context, moduleName, platform);
  }
  return context.resolveRequest(context, moduleName, platform);
};

// Seed plugin bundle is stored as .txt so Metro treats it as an asset, not JS.
config.resolver.assetExts = [...new Set([...(config.resolver.assetExts ?? []), 'txt'])];

module.exports = config;
